import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/component/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="mt-12 mb-24 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
      <h1 className="text-6xl">Unleash Creative Freedom Instantly</h1>
        <p className="text-2xl mt-4">
            Our AI-powered icon generator transforms your ideas into vibrant icons in seconds, saving you time and money.
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generate your Icons
        </PrimaryLinkButton>
      </div>
      <Image
        src="/banner.png"
        alt="an image of a bunch of nice looking icons"
        width="400"
        height="300"
        className="order-first sm:-order-none"
      />
    </section>
  );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>DALL-E icon generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center">
      <HeroBanner />

      </main>
    </>
  );
};

export default HomePage;
